"""Rotas da API do domínio Alunos."""

from django.urls import path

from apps.alunos.api.views import (
    AlunosAtivosPeriodoTurmaView,
    AlunosAtivosTurmaView,
    AlunosPorCodigosEAnoView,
    AlunosPorCodigosView,
    AlunosTurmaView,
    AutocompleteAlunosAtivosView,
    AutocompleteAlunosUeView,
    BuscarAlunosDaUeView,
    BuscaTurmasDoAlunoComHistoricoView,
    BuscaTurmasDoAlunoPorSituacaoMatriculaView,
    BuscaTurmasDoAlunoView,
    CodigosTurmasRegularesAlunoView,
    DadosAcompanhamentoEscolarContratoView,
    DadosAcompanhamentoEscolarView,
    DadosResponsavelResumidoView,
    DadosResponsavelView,
    FiliacaoAlunoView,
    InformacoesAlunosTurmaView,
    InformacoesAlunoView,
    MatriculasAlunoEscolaView,
    MatriculasAnoAtualView,
    MatriculasAnosAnterioresView,
    NecessidadesEspeciaisAlunoView,
    QuantidadeAlunosPorTurmaEscolaView,
    QuantidadeMatriculadosCCContratoView,
    QuantidadeMatriculadosContratoView,
    QuantidadeMatriculadosPorAnoCCView,
    QuantidadeMatriculadosView,
    ResponsaveisDreUeTurmaView,
    ResponsavelAlunoView,
    TotalAlunosAtivosPorPeriodoView,
    TotalMatriculasPorTurnoDreView,
    TotalMatriculasPorTurnoUeView,
)

urlpatterns = [
    path(
        "anos-letivos/<str:ano_letivo>/alunos/<str:codigo_aluno>/"
        "codigos-turmas-regulares",
        CodigosTurmasRegularesAlunoView.as_view(),
        name="codigos-turmas-regulares-aluno",
    ),
    path(
        "<str:codigo_aluno>/turmas/",
        BuscaTurmasDoAlunoView.as_view(),
        name="busca-turmas-do-aluno",
    ),
    path(
        "<str:codigo_aluno>/turmas/anos_letivos/<str:ano_letivo>/"
        "matricula_turma/<str:filtrar_situacao_matricula>/"
        "tipo_turma/<str:tipo_turma>",
        BuscaTurmasDoAlunoPorSituacaoMatriculaView.as_view(),
        name="busca-turmas-do-aluno-por-situacao-matricula",
    ),
    path(
        "<str:codigo_aluno>/turmas/anos_letivos/<str:ano_letivo>/"
        "historico/<str:historico>/"
        "filtrar_situacao/<str:filtrar_situacao>/"
        "tipo_turma/<str:tipo_turma>",
        BuscaTurmasDoAlunoComHistoricoView.as_view(),
        name="busca-turmas-do-aluno-com-historico",
    ),
    path(
        "ues/<str:codigo_ue>/anos_letivos/<str:ano_letivo>",
        BuscarAlunosDaUeView.as_view(),
        name="buscar-alunos-da-ue",
    ),
    path(
        "ues/<str:codigo_ue>/anos_letivos/<str:ano_letivo>/autocomplete",
        AutocompleteAlunosUeView.as_view(),
        name="autocomplete-alunos-ue",
    ),
    path(
        "ues/<str:ue_codigo>/autocomplete/ativos",
        AutocompleteAlunosAtivosView.as_view(),
        name="autocomplete-alunos-ativos",
    ),
    path(
        "ativos/anos/<str:ano_turma>/anos-letivos/<str:ano_letivo>/"
        "inicio/<str:data_inicio>/fim/<str:data_fim>",
        TotalAlunosAtivosPorPeriodoView.as_view(),
        name="total-alunos-ativos-por-periodo",
    ),
    path(
        "turmas/<str:codigo_turma>/ativos/<str:data_referencia_fim>",
        AlunosAtivosPeriodoTurmaView.as_view(),
        name="alunos-ativos-periodo-turma",
    ),
    path(
        "turmas/<str:codigo_turma>/ativos",
        AlunosAtivosTurmaView.as_view(),
        name="alunos-ativos-turma",
    ),
    path(
        "turmas/<str:codigo_turma>/",
        AlunosTurmaView.as_view(),
        name="alunos-turma",
    ),
    path(
        "<str:codigo_aluno>/necessidades-especiais",
        NecessidadesEspeciaisAlunoView.as_view(),
        name="necessidades-especiais-aluno",
    ),
    path(
        "ano_letivo/<str:ano_letivo>/alunos",
        AlunosPorCodigosEAnoView.as_view(),
        name="alunos-por-codigos-e-ano",
    ),
    path(
        "alunos",
        AlunosPorCodigosView.as_view(),
        name="alunos-por-codigos",
    ),
    path(
        "<str:codigo_aluno>/informacoes",
        InformacoesAlunoView.as_view(),
        name="informacoes-aluno",
    ),
    path(
        "<str:codigo_turma>/turma/informacoes",
        InformacoesAlunosTurmaView.as_view(),
        name="informacoes-alunos-turma",
    ),
    path(
        "ano-letivo/<str:ano_letivo>/matriculados",
        QuantidadeMatriculadosPorAnoCCView.as_view(),
        name="quantidade-matriculados-cc",
    ),
    path(
        "ano-letivo/<str:ano_letivo>/matriculados/contrato",
        QuantidadeMatriculadosCCContratoView.as_view(),
        name="quantidade-matriculados-cc-contrato",
    ),
    path(
        "ano-letivo/<str:ano_letivo>/matriculados/quantidade",
        QuantidadeMatriculadosView.as_view(),
        name="quantidade-matriculados",
    ),
    path(
        "ano-letivo/<str:ano_letivo>/matriculados/quantidade/contrato",
        QuantidadeMatriculadosContratoView.as_view(),
        name="quantidade-matriculados-contrato",
    ),
    path(
        "dados-acompanhamento-escolar",
        DadosAcompanhamentoEscolarView.as_view(),
        name="dados-acompanhamento-escolar",
    ),
    path(
        "dados-acompanhamento-escolar/contrato",
        DadosAcompanhamentoEscolarContratoView.as_view(),
        name="dados-acompanhamento-escolar-contrato",
    ),
    path(
        "responsaveis",
        ResponsaveisDreUeTurmaView.as_view(),
        name="responsaveis-dre-ue-turma",
    ),
    path(
        "responsaveis/<str:cpf_responsavel>",
        DadosResponsavelView.as_view(),
        name="dados-responsavel",
    ),
    path(
        "responsaveis/<str:cpf_responsavel>/resumido",
        DadosResponsavelResumidoView.as_view(),
        name="dados-responsavel-resumido",
    ),
    path(
        "<str:codigo_aluno>/responsaveis/filiacao",
        FiliacaoAlunoView.as_view(),
        name="filiacao-aluno",
    ),
    path(
        "<str:codigo_aluno>/responsaveis/<str:cpf_responsavel>",
        ResponsavelAlunoView.as_view(),
        name="responsavel-aluno",
    ),
    path(
        "matriculas",
        MatriculasAnoAtualView.as_view(),
        name="matriculas-ano-atual",
    ),
    path(
        "matriculas/anos-anteriores",
        MatriculasAnosAnterioresView.as_view(),
        name="matriculas-anos-anteriores",
    ),
    path(
        "matriculas/escolas/<str:ue_codigo>/quantidades",
        TotalMatriculasPorTurnoUeView.as_view(),
        name="matriculas-quantidades-ue",
    ),
    path(
        "matriculas/escolas/dre/<str:dre_codigo>/quantidades",
        TotalMatriculasPorTurnoDreView.as_view(),
        name="matriculas-quantidades-dre",
    ),
    path(
        "escolas/<str:codigo_escola>/alunos/quantidade",
        QuantidadeAlunosPorTurmaEscolaView.as_view(),
        name="quantidade-alunos-por-turma-escola",
    ),
    path(
        "escolas/<str:codigo_escola>/aluno/<str:codigo_aluno>/matriculas",
        MatriculasAlunoEscolaView.as_view(),
        name="matriculas-aluno-escola",
    ),
]
